[package]
name = "sqli"
version = "0.1.0"
edition = "2021"

[dependencies]
my_request = { path = "../my_request" }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
futures = "0.3.30"
log = "0.4.22"
urlencoding = "2.1.3"
